// Search/API reducer
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const SEARCH_API = "SEARCH_API";
export const GENRES_FROM_API = "GENRES_FROM_API";
export const GET_POPULAR_MOVIES_FROM_API = "GET_POPULAR_MOVIES_FROM_API";
export const GET_DAY_TRENDING_MOVIES_FROM_API =
  "GET_DAY_TRENDING_MOVIES_FROM_API";
export const GET_WEEK_TRENDING_MOVIES_FROM_API =
  "GET_WEEK_TRENDING_MOVIES_FROM_API";

// Movie reducer
export const ADD_WATCHED_MOVIE = "ADD_WATCHED_MOVIE";
export const ADD_TO_WATCH_MOVIE = "ADD_TO_WATCH_MOVIE";
export const REMOVE_WATCHED_MOVIE = "REMOVE_WATCHED_MOVIE";
export const REMOVE_TO_WATCH_MOVIE = "REMOVE_TO_WATCH_MOVIE";
